modLoader = "javafml"
loaderVersion = "*"
issueTrackerURL = "https://github.com/ThePandaOliver/Multiloader-Template/issues"
license = "${mod_license}"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
authors = "${mod_authors}"
description = "${mod_description}"
logoFile = "assets/${mod_id}/icon.png"

[[dependencies."${mod_id}"]]
modId = "forge"
mandatory = true
versionRange = "[${loader_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "minecraft"
mandatory = true
versionRange = "[${minecraft_version},)"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "${mod_id}.mixins.json"
